spring:
  application:
    name: Shimmer
  data:
    mongodb:
      uri: mongodb://shimmerapp:Ab9(gQua*9@ds040489.mlab.com:40489/shimmer_dev
  jackson:
    serialization:
      indent_output: true
server:
  port: 8080
security:
  basic:
    enabled: false
logging:
  file: shimmer.log

openmhealth:
  shim:
    server:
      callbackUrlBase: http://localhost:59363

    #NOTE: Uncomment and fill in the clientId/clientSecret with your credentials if you're not using the UI
    #NOTE: Uncomment and set partnerAccess to true if your credentials for a given API have partner access
    #NOTE: Uncomment and fill in your serialValues for iHealth, otherwise the iHealth shim will not work correctly
    #ihealth:
    #  serialValues:
    #    SC: [YOUR_SC_VALUE]
    #    sportSV: [YOUR_SV_VALUE_FOR_THE_SPORT_ENDPOINT]
    #    bloodPressureSV: [YOUR_SV_VALUE_FOR_THE_BLOOD_PRESSURE_ENDPOINT]
    #    spo2SV: [YOUR_SV_VALUE_FOR_THE_SPO2_ENDPOINT]
    #    weightSV: [YOUR_SV_VALUE_FOR_THE_WEIGHT_ENDPOINT]
    #    bloodGlucoseSV: [YOUR_SV_VALUE_FOR_THE_BLOOD_GLUCOSE_ENDPOINT]
    #    activitySV: [YOUR_SV_VALUE_FOR_THE_ACTIVITY_ENDPOINT]
    #    sleepSV: [YOUR_SV_VALUE_FOR_THE_SLEEP_ENDPOINT]
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    fitbit:
      partnerAccess: true
      clientId: 227VX4
      clientSecret: 9d60e46eade1673cb2ce6ba9999b816c
    #fatsecret:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #jawbone:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #misfit:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #runkeeper:
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #withings:
    #  partnerAccess: true
    #  clientId: [YOUR_CLIENT_ID]
    #  clientSecret: [YOUR_CLIENT_SECRET]
    #healthvault:
    #  clientId: [YOUR_CLIENT_ID]
    googlefit:
      clientId: 531482589768-gdjv1ojl77hge4ssg4n15r3dipsv9o2g.apps.googleusercontent.com
      clientSecret: 1L63MQDI3JPr3h1n99VyqY4N
